version: '3'
services:
  graph-node:
    networks:
     - br0
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8020:8020'
    expose:
      - '8001/tcp'
      - '8030/tcp'
      - '8040/tcp'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: ''
      GRAPH_LOG: info
  ipfs:
    networks:
     - br0
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - /data/ipfs:/data/ipfs
  postgres:
    networks:
     - br0
    image: postgres
    expose:
      - '5432/tcp'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - /data/postgres:/var/lib/postgresql/data

networks:
  br0:
    external:
      name: br0
